version: '3.8'

services:
  intellicv-main:
    build: .
    container_name: intellicv-ai-main
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      # Mount data directories for persistence
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.intellicv.rule=Host(`localhost`)"
      - "traefik.http.services.intellicv.loadbalancer.server.port=8501"

networks:
  default:
    name: intellicv-network