services:
  admin-portal:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: intellicv-admin-minimal
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: intellicv-minimal-network